#!/usr/bin/bash
# a BASH user input test

read -p 'Name: ' username
read -p 'Visit number: ' visitnum

dir=$(dirname $0)

$dir/python_test $username $visitnum

# comment for git update test

#another comment for git test
