#!/usr/bin/python3

import pygame


pygame.init()

i = 0
clock=pygame.time.Clock()

time = 0
while i < 10:
	clock.tick_busy_loop(250) 
	time += clock.get_time()	
	print(i, pygame.time.get_ticks(), time, clock.get_time())	
	i += 1
 
